### ISSUE TITLE
how to connect correctly to NDN-DPDK

### ISSUE THREAD

**Issue by Code-shaker** [yoursunny/NDNts-video-server#3]
As you mentioned:

https://github.com/usnistgov/ndn-dpdk/issues/19#issuecomment-892802152
> If you want to connect NDNts-video-server to NDN-DPDK forwarder, you can replace `await openUplinks();` with something like:
>
> 
> ```ts
> // at top of the module; of course, you need to install this package first
> import { openFace } from "@ndn/dpdkmgmt";
> 
> // in place of `openUplinks()`
> await openFace({
>   localHost: "172.26.6.2", // IPv4 address of the NDNts-video-server container
>   gqlServer: "http://172.26.6.3:3030", // GraphQL endpoint of NDN-DPDK
> });
> ```
> 

I already prepare ndn/dpdkmgmt 

but I am not shure about the parameter for: 

localHost: "I choose the IPv4 address for eth0 ", // IPv4 address of the NDNts-video-server container

gqlServer: "http://172.26.6.3:3030", // GraphQL endpoint of NDN-DPDK

**Comment by yoursunny** [comment]
If NDN-DPDK and NDNts are both running on the host system (not in a container):

* gqlServer: 127.0.0.1
* localHost: 127.0.0.1

If NDN-DPDK is in a container, but NDNts is in the host system:

* gqlServer: container's IP address
* localHost: IP address of the host system's network adapter; you can find this by `docker network inspect bridge | jq -r '.[].IPAM.Config[].Gateway'` (if you are using a custom Docker network instead of the default, substitute "bridge" with Docker network name)

If both are in containers:

* gqlServer: NDN-DPDK container's IP address
* localHost: NDNts container's IP address
* Both containers must be in the same Docker network (either the default bridge network or a custom network).

**Comment by yoursunny** [comment]
I just did some updates in NDNts (commit https://github.com/yoursunny/NDNts/commit/10ed9fa0ebcc675a4fb719a1caa00e171bead35c).

* NDN-DPDK connection is integrated into the `@ndn/cli-common` package
* localHost option is no longer needed, except the rare case that NDNts side is behind NAT or has unusual firewall settings

No code modification is needed to connect to NDN-DPDK from a NDNts app that uses `@ndn/cli-common` package.

If NDN-DPDK and NDNts are both running on the host system, all you need is one environment variable:

```bash
NDNTS_UPLINK=ndndpdk:
```

If NDN-DPDK is in a container and NDNts is running on the host system, you need another environment variable:

```bash
NDNTS_NDNDPDK_GQLSERVER=http://192.0.2.1:3030
# refer to "NDN-DPDK Docker container" page on how to find the correct IP address
```

You may write the environment variables into **.env** file.

**Comment by Code-shaker** [comment]
Ok I will try it.

How to prepare NDNts for livestream using chunks to transmit media-sources.

Do you have some advices?

**Comment by yoursunny** [comment]
> livestream

NDNts-video-server is a repository for recorded videos.
It cannot do livestream.

For live stream, you need NDNts-homecam.
https://homecam.ndn.today
(it's quite finicky since the last update;  recommend Firefox browser)

**Comment by Code-shaker** [comment]
Ok, I will firstly test it just with to transmit video-files

So what should be prepared to start

**Comment by Code-shaker** [comment]
Another question is NDNts-homecam compatible to NDN-DPDK?

**Comment by yoursunny** [comment]
> is NDNts-homecam compatible to NDN-DPDK?

No, it's a web application that runs in browser.

**Comment by Code-shaker** [comment]
Yes right as you mentioned that its not possible to connect Browser with NDN-DPDK

**Comment by Code-shaker** [comment]
Could I just use the code you have given on `usage`, because I want transmit video by smaller chunks

**Comment by yoursunny** [comment]
> Could I just use the code you have given on `usage`

Of course you can.
The **serve** subcommand starts a producer.
All other commands interacts with the database only, and does not have networking.
You need a consumer separately.

**Comment by Code-shaker** [comment]
I am not so clear about, what represents a DataTape (of local video) exactly?

**Comment by yoursunny** [comment]
> what represents a DataTape

**DataTape** is a file or stream that consists of a sequence of Data packets. As a file type, DataTape may be used to transfer packets between repo instances.
https://ndnts-docs.ndn.today/typedoc/modules/repo_api.html

**Comment by Code-shaker** [comment]
Ok thanks
