### ISSUE TITLE
video-prototype: transfer videoFile("/sample_video") through NFD with NDNts

### ISSUE THREAD

**Issue by Code-shaker** [yoursunny/NDNts-video-server#4]
-without player
-on local machine
```text
                                    2.interest
|-----------| 1.publish |----------| to fetch  |-----------|
|producer.js|---------->|          |<----------|consumer.js|
|/v_chunk[i]|           |   NFD    |           |/v_chunk[i]|
|-----------|---------->|          |---------->|-----------|
              3.sends   |----------| 4.sends           
               data                  data
       =                                              =
/sample_video                --------->>>        /sample_video
```

How to: 

-encode videoFile for chunks, should I work with a framework (ffmpeg or gstreamer)
("https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#fluent-ffmpeg-api-for-nodejs-")

-fetch the videoFile ("https://ndnts-docs.ndn.today/typedoc/modules/segmented_object.html")

**Comment by yoursunny** [comment]
> -encode videoFile for chunks, should I work with a framework (ffmpeg or gstreamer)

See usage instructions in README.
Look for `encode.sh` and `node ./cli.cjs prepare` commands.

The `encode.sh` script uses ffmpeg and [shake-packager](https://github.com/google/shaka-packager).
You may edit this script if you want to use different video codecs.

> -fetch the videoFile

You should use the [NDNts-video webapp](https://github.com/yoursunny/NDNts-video).

**Comment by Code-shaker** [comment]
would it be possilble to work on "Node.js" 
[Stream](https://github.com/nodejs/node/blob/master/doc/api/stream.md)

**Comment by Code-shaker** [comment]
I saw some examples of [Node.js](https://github.com/webdevjourneyWDJ/Node-JS-Streams) would it possible to use it?
Because of [OpenStream](https://ndnts-docs.ndn.today/typedoc/modules/repo_api.datatape) it seems you use it already

**Comment by yoursunny** [comment]
Yes, you can use `DataTape.openStream` function to create a `DataTape` object from a Node.js stream such as a file or a TCP socket.
This has nothing to do with videos though.

**Comment by Code-shaker** [comment]
I am not clear, how exactly I should prepare a videoFile to transfer it trough NFD, sry need help

**Comment by yoursunny** [comment]
See the README "usage" section, especially these commands:

1. encode.sh: this converts input video to DASH segments
2. node ./cli.cjs prepare: this converts DASH segments to DataTape (NDN packets)
3. node ./cli.cjs import: this imports DataTape into a repo
4. node ./cli.cjs serve: this starts a NDN producer that serves packets in the repo

Then you need [NDNts-video webapp](https://github.com/yoursunny/NDNts-video) as the consumer to retrieve files from the repo.

**Comment by Code-shaker** [comment]
node ./cli.cjs prepare --prefix $VIDEO_PREFIX --path $VIDEO_TEMP > video.dtar
```text
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'hard-rejection'
Require stack:
- /home/vmadmin/NDNts-video-server/cli.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/vmadmin/NDNts-video-server/cli.cjs:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/vmadmin/NDNts-video-server/cli.cjs' ]
}
```

**Comment by yoursunny** [comment]
> Error: Cannot find module 'hard-rejection'

Did you follow the "installation" steps in README?
Specifically, did you run `npm install --production` and was it successful?

**Comment by Code-shaker** [comment]
I will run it again

**Comment by Code-shaker** [comment]
ok it works, but how integrate a videoFile I try it on the content.json file?

**Comment by Code-shaker** [comment]
another question, 

how to put those chunks trough my producer to consumer?
```
 readStream.on('data', (chunk) => {
                console.log("chunkSize:", chunk.length, "bytes");
                writeStream.write(chunk);
            })
```

**Comment by yoursunny** [comment]
> how integrate a videoFile I try it on the content.json file?

Yes, you need to put the NDN name of each video's DASH manifest in `content.json` of the webapp.

---

On the video server side, you need to ensure the producer is reachable from the global NDN testbed, which in turn requires setting up a certificate for prefix registrations.

The following commands obtain a certificate from my Personal CA and setup the video server to use this certificate:

```bash
npm i -g https://ndnts-nightly.ndn.today/keychain-cli.tgz
source .env
curl -sfL https://gist.githubusercontent.com/yoursunny/54db5b27f9193859b7d1c83f0aeb8d6d/raw/ca-profile.data.base64 | base64 -d > profile.data
CAPREFIX=$(ndnts-keychain ndncert03-show-profile --profile profile.data | sed -n '/^CA prefix:/ s/^[^:]*: // p')
KEYNAME=$(ndnts-keychain gen-key $CAPREFIX/$(hostname -s)-$(basename $PWD) | tee /dev/stderr | awk -F/ -vOFS=/ '{ NF-=2; print }')
CERTNAME=$(ndnts-keychain ndncert03-client --profile profile.data --key $KEYNAME --challenge nop | tee /dev/stderr)
sed -i '/NDNTS_KEY=/ s|=.*|='$CERTNAME'|' .env
```

Then, edit `.env` and include the video prefix in `REPO_PREFIXES` variable.
Start the producer.
After a few minutes, the prefix announcement should show up on https://nlsr-status.ndn.today , and the player will work.

**Comment by Code-shaker** [comment]
> another question,
> 
> how to put those chunks trough my producer to consumer?
> 
> ```
>  readStream.on('data', (chunk) => {
>                 console.log("chunkSize:", chunk.length, "bytes");
>                 writeStream.write(chunk);
>             })
> ```

[segmentedObject](https://ndnts-docs.ndn.today/typedoc/modules/segmented_object.html) should be an option to try something

**Comment by Code-shaker** [comment]
outputs in-order data chunks as a readable stream.

**Comment by Code-shaker** [comment]
```
producer:                                       >>>   consumer:
takes input from readable streams                     outputs in-order data chunks as a readable stream
```
where is it implemented? [prepare](https://github.com/yoursunny/NDNts-video-server/blob/main/src/prepare.js)
Do you have anohter example?

**Comment by yoursunny** [comment]
`@ndn/segmented-object` is more like a file transfer, with no video semantics: it cannot adjust video resolution based on available bandwidth.
See `@ndn/cat` package for examples.

**Comment by Code-shaker** [comment]
1. Show v.file

something like:
const readStream = createReadStream('./sample_video.mp4');


2. v.file write to chunks


3. send chunks trough NFD to consumer


4. put those chunks to a v.file

**Comment by Code-shaker** [comment]
its just should stream bit by bit
```
**1. Show v.file**

something like:
const readStream = createReadStream('./sample_video.mp4');


**2. v.file write to chunks**

something like:
readStream.pipe(data.content).on('error', console.error);

or

 /** Iterate over payload chunks in segment number order. */
    chunks: () => AsyncIterable:Uint8Array;

**3. send chunks trough NFD to consumer**

?

**4. put those chunks to a v.file**

Write all chunks to the destination stream.--fetch--
pipe: (dest: NodeJS.WritableStream) => Promise(void);
```


need some correctoin from your side

**Comment by yoursunny** [comment]
That's a file transfer, not a video application.
Use `@ndn/cat` package for that.

**Comment by Code-shaker** [comment]
> Use `@ndn/cat` package for that.

ok it is for video applications as you mentioned

**Comment by Code-shaker** [comment]
>dd if=/dev/urandom of=/tmp/1.bin bs=1M count=1

sry what is the expression ?

**Comment by Code-shaker** [comment]
could you explain:
dd if=/dev/urandom of=/tmp/1.bin bs=1M count=1

and:
diff /tmp/1.bin /tmp/2.bin
rm /tmp/1.bin /tmp/2.bin

**Comment by yoursunny** [comment]
> dd if=/dev/urandom of=/tmp/1.bin bs=1M count=1

Fill a file with random data.

> diff /tmp/1.bin /tmp/2.bin

Compare two files, to ensure it's transferred correctly.

> rm /tmp/1.bin /tmp/2.bin

Delete files.


You should have consulted Unix manpages, instead of asking here, as these commands do not belong to NDNts.
You can access the manpage by typing `man dd` on the console.

**Comment by Code-shaker** [comment]
sry I just try to understand [cat](https://github.com/yoursunny/NDNts/tree/ef8be94f99ebcfffd9a723972d5686ce7c203402/packages/cat) it seems to belong on NDNts, I am not familiar I have to learn it

**Comment by yoursunny** [comment]
`cat` is part of Unix.
`ndncat` aka `@ndn/cat` is part of NDNts.

**Comment by Code-shaker** [comment]
could you teach me about @ndn/cat

**Comment by yoursunny** [comment]
> could you teach me about @ndn/cat

See README in the package folder.

**Comment by Code-shaker** [comment]
for my _video-prototype_ I also have to use **ndn6-tools** to serve the file

**Comment by Code-shaker** [comment]
sry, how to etalbish the package @ndn/cat to use it?
so far its listed on my package.json file but it couldn't find the command and run "npm install"
how to do install it correctly?

**Comment by Code-shaker** [comment]
sry, how to install those package I started with "wget" and then "tar xvfz cat.tgz", what I have to do next? just "npm install" ?

**Comment by yoursunny** [comment]
`@ndn/cat` `@ndn/repo-cli` `@ndn/keychain-cli` are CLI commands and they are meant be installed as global packages.
Use [npm install](https://docs.npmjs.com/cli/v7/commands/npm-install/) with **-g** flag.

**Comment by Code-shaker** [comment]
it seems to work, but I also  got:

```
Not enough non-option arguments: got 0, need at least 1
YError: Not enough non-option arguments: got 0, need at least 1
    at Object.fail (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/usage.js:59:26)
    at Object.nonOptionCount (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/validation.js:25:27)
    at file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:1425:74
    at file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:1143:13
    at maybeAsyncResult (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at YargsInstance.[validateAsync] (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:1142:16)
    at YargsInstance.[runYargsParserAndExecuteCommands] (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:1403:55)
    at YargsInstance.parse (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:674:63)
    at YargsInstance.parseAsync (file:///home/vmadmin/ndnts/node_modules/yargs/build/lib/yargs-factory.js:704:35)
    at file:///home/vmadmin/ndnts/ndn_cat/lib/main_node.js:22:6
```

**Comment by yoursunny** [comment]
> Not enough non-option arguments: got 0, need at least 1

Follow the command syntax displayed above this error message.

**Comment by Code-shaker** [comment]
ok I try it once again, in the end I got:

**Comment by yoursunny** [comment]
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'memif' imported from /home/vmadmin/.nvm/versions/node/v16.8.0/lib/node_modules/@ndn/cat/node_modules/@ndn/dpdkmgmt/lib/memif-transport_node.js

This is possibly a new bug.
`memif` is supposed to be an optional dependency.
I'll check it.

**Comment by yoursunny** [comment]
> > Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'memif' imported from /home/vmadmin/.nvm/versions/node/v16.8.0/lib/node_modules/@ndn/cat/node_modules/@ndn/dpdkmgmt/lib/memif-transport_node.js
> 
> This is possibly a new bug.
> `memif` is supposed to be an optional dependency.
> I'll check it.

Fixed in https://github.com/yoursunny/NDNts/commit/75bd552f28d6f74b3b1e1eec2519d74b544aa449
